# Generated by Django 6.1.1 on 2026-09-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='hostelhub.resident')),
            ],
        ),
    ]
